[[configs]]
environment = "development"
address = "localhost"
port = 8000
workers = 4
[configs.database]
adapter = "postgresql"
db_name = "blog_development"
pool = 5

[[configs]]
environment = "staging"
address = "localhost"
port = 800
workers = 5
[configs.database]
adapter = "postgresql"
db_name = "blog_staging"
pool = 5

[[configs]]
environment = "production"
address = "localhost"
port = 800
workers = 5
[configs.database]
adapter = "postgresql"
db_name = "blog_prodction"
pool = 5